name: Compile Sass

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/**
      - "*.scss"

jobs:
  compile:
    runs-on: ubuntu-latest
    outputs:
      commitSha: ${{steps.commit.outputs.commit_long_sha}}

    steps:
      - uses: actions/checkout@v4
      - name: Compile
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: ./app.scss
          destination: ./betterdiscord/main.css
          outputStyle: expanded
      - uses: EndBug/add-and-commit@v9
        id: commit
        with:
          default_author: github_actions
          message: "chore: build"
          fetch: true

  build:
    needs: compile
    uses: ./.github/workflows/gh-pages.yml
    with:
      sha: ${{needs.compile.outputs.commitSha}}
